// This file is auto-generated by scripts/register-mock-agents.ts — do not edit manually.

export interface RegisteredAgent {
  foroId: bigint;
  name: string;
}

export const REGISTERED_AGENTS: RegisteredAgent[] = [
  // { foroId: 8n, name: 'agent-uni' },
  // { foroId: 9n, name: 'agent-makerdao' },
  // { foroId: 10n, name: 'agent-aave' },
  // { foroId: 11n, name: 'agent-compound' },
  // { foroId: 12n, name: 'agent-curve' },
  // { foroId: 13n, name: 'agent-lido' },
  // { foroId: 14n, name: 'agent-yearn' },
  // { foroId: 15n, name: 'agent-balancer' },
  // { foroId: 16n, name: 'agent-frax' },
  // { foroId: 17n, name: 'agent-convex' },
];
