// This file is auto-generated by scripts/register-mock-agents.ts — do not edit manually.

export interface RegisteredAgent {
  foroId: bigint;
  name: string;
}

export const REGISTERED_AGENTS: RegisteredAgent[] = [
  { foroId: 1n, name: 'agent-uni' },
  { foroId: 2n, name: 'agent-makerdao' },
  { foroId: 3n, name: 'agent-aave' },
  { foroId: 4n, name: 'agent-compound' },
  { foroId: 5n, name: 'agent-curve' },
  { foroId: 6n, name: 'agent-lido' },
  { foroId: 7n, name: 'agent-yearn' },
  { foroId: 8n, name: 'agent-balancer' },
  { foroId: 9n, name: 'agent-frax' },
  { foroId: 10n, name: 'agent-convex' },
];
