/**
 * Generate TypeScript types from Foundry contract ABIs
 * 
 * This script:
 * 1. Reads contract ABIs from Foundry out/ directory
 * 2. Extracts essential contract information (address, ABI)
 * 3. Generates TypeScript type definitions
 * 4. Creates exports for use in backend and frontend
 */

import * as fs from 'fs';
import * as path from 'path';

interface ContractArtifact {
  abi: any[];
  bytecode: {
    object: string;
  };
}

interface DeploymentInfo {
  [contractName: string]: string; // contract name -> address
  chainId?: number;
  deployedAt?: number;
}

const CONTRACTS_DIR = path.join(__dirname, '../../../contracts');
const OUT_DIR = path.join(CONTRACTS_DIR, 'out');
const DEPLOYMENTS_FILE = path.join(CONTRACTS_DIR, 'deployments.json');
const OUTPUT_DIR = path.join(__dirname, '..');

// Contracts to export
const CONTRACTS = [
  'ForoRegistry',
  'AgentVault',
  'MockERC8004',
  'IForoRegistry',
  'IAgentVault',
  'IERC8004'
];

function readArtifact(contractName: string): ContractArtifact | null {
  const artifactPath = path.join(OUT_DIR, `${contractName}.sol`, `${contractName}.json`);
  
  if (!fs.existsSync(artifactPath)) {
    console.warn(`⚠️  Artifact not found: ${contractName}`);
    return null;
  }

  try {
    const content = fs.readFileSync(artifactPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error(`❌ Failed to read ${contractName}:`, error);
    return null;
  }
}

function readDeployments(): DeploymentInfo {
  if (!fs.existsSync(DEPLOYMENTS_FILE)) {
    console.warn('⚠️  deployments.json not found. Contracts not yet deployed.');
    return {};
  }

  try {
    const content = fs.readFileSync(DEPLOYMENTS_FILE, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error('❌ Failed to read deployments.json:', error);
    return {};
  }
}

function generateContractsFile() {
  const deployments = readDeployments();
  const contracts: Record<string, { abi: any[]; address?: string }> = {};

  // Read all contract ABIs
  for (const contractName of CONTRACTS) {
    const artifact = readArtifact(contractName);
    if (artifact) {
      contracts[contractName] = {
        abi: artifact.abi,
        address: deployments[contractName]
      };
    }
  }

  // Generate TypeScript file
  const output = `/**
 * Generated contract ABIs and addresses
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-types.ts
 * 
 * To regenerate: pnpm run generate-types
 */

export interface ContractInfo {
  abi: any[];
  address?: string;
}

export const contracts = ${JSON.stringify(contracts, null, 2)} as const;

// Contract addresses (if deployed)
export const addresses = {
  ForoRegistry: ${JSON.stringify(deployments.ForoRegistry || null)},
  AgentVault: ${JSON.stringify(deployments.AgentVault || null)},
  MockERC8004: ${JSON.stringify(deployments.MockERC8004 || null)},
  protocolTreasury: ${JSON.stringify(deployments.protocolTreasury || null)},
} as const;

// Network info
export const deployment = {
  chainId: ${deployments.chainId || 'undefined'},
  deployedAt: ${deployments.deployedAt || 'undefined'},
  minKeeperStake: ${JSON.stringify(deployments.minKeeperStake || null)},
  testFeeAmount: ${JSON.stringify(deployments.testFeeAmount || null)},
} as const;

// Type exports for contract functions
export type ForoRegistryABI = typeof contracts.ForoRegistry.abi;
export type AgentVaultABI = typeof contracts.AgentVault.abi;
export type MockERC8004ABI = typeof contracts.MockERC8004.abi;
`;

  const outputPath = path.join(OUTPUT_DIR, 'contracts.ts');
  fs.writeFileSync(outputPath, output);
  console.log('✅ Generated contracts.ts');
}

function generateEnumTypes() {
  const output = `/**
 * Generated enum types from Solidity contracts
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-types.ts
 */

export enum AgentStatus {
  PENDING = 0,
  PROBATION = 1,
  VERIFIED = 2,
  ELITE = 3,
  FAILED = 4
}

export enum TestJobStatus {
  REQUESTED = 0,
  COMMITTED = 1,
  REVEALED = 2,
  SUBMITTED = 3,
  CONTESTED = 4,
  FINALIZED = 5,
  REFUNDED = 6
}

export enum ResultType {
  SUCCESS = 0,
  FAILED_ENDPOINT = 1
}

export enum FailureReason {
  TIMEOUT = 0,
  UNREACHABLE = 1,
  INVALID_RESPONSE = 2,
  ENDPOINT_ERROR = 3,
  TEE_UNAVAILABLE = 4
}
`;

  const outputPath = path.join(OUTPUT_DIR, 'enums.ts');
  fs.writeFileSync(outputPath, output);
  console.log('✅ Generated enums.ts');
}

function generateIndexFile() {
  const output = `/**
 * Shared types package for Foro protocol
 * Exports contract ABIs, types, and deployment info
 */

export * from './contracts';
export * from './enums';
export * from './agent';
export * from './keeper';
`;

  const outputPath = path.join(OUTPUT_DIR, 'index.ts');
  fs.writeFileSync(outputPath, output);
  console.log('✅ Generated index.ts');
}

// Main execution
console.log('🔨 Generating TypeScript types from contract ABIs...\n');

generateContractsFile();
generateEnumTypes();
generateIndexFile();

console.log('\n✅ Type generation complete!');
console.log('📦 Contracts available in packages/types/contracts.ts');
console.log('📦 Enums available in packages/types/enums.ts');
